Parameters:
  NameOfService:
    Description: The name of the service this stack is to be used for.
    Type: String
  InstanceTypeParameter:
    Description: Enter t2.micro, t2.small, or t3.small. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.small
  KeyName:
    Description: Name of EC2 login key
    Type: AWS::EC2::KeyPair::KeyName

Mappings: 
  AMIRegionMap: 
    us-east-1:
      MyAMI1: ami-01816d07b1128cd2d
    us-east-2:
      MyAMI1: ami-0b4624933067d393a
    us-west-2:
      MyAMI1: ami-07d9cf938edb0739b

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init: 
        config:
          packages:
            yum:
              php8.1: []
              httpd: []
              wget: []
              unzip: []
              git: []
          commands:
            update_and_install_packages:
              command: "yum update -y && yum install -y php wget httpd unzip git"
            test:
              command: "wget https://www.tooplate.com/zip-templates/2137_barista_cafe.zip && unzip 2137_barista_cafe.zip && cp -r 2137_barista_cafe/* /var/www/html"
          files:
            /var/www/html/hello.html:
              content: !Sub
                <!DOCTYPE html>
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Document</title>
                </head>
                <body>
                    <h1>Welcome to CloudFormation</h1>
                    <p>This site is deployed bt CloudFormation</p>
                </body>
                </html>
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AMIRegionMap
        - !Ref AWS::Region
        - MyAMI1
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, !Ref NameOfService, in, !Ref "AWS::Region"]]
      SecurityGroups:
        - !Ref VprofileSG
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash -xe
            # Ensure AWS CFN Bootstrap is the latest
            yum install -y aws-cfn-bootstrap
            # Install the files and packages from metadata 
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServer --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServer --region ${AWS::Region}
  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from MyIP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 178.36.118.226/32

Outputs:
  PrintSomeInfo:
    Value: !GetAtt
      - WebServer
      - PublicDnsName